"""device_family

Revision ID: 7f7ae01a985c
Revises: 920d7a54afc3
Create Date: 2026-09-29 20:59:02.799015

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f7ae01a985c"
down_revision: str | Sequence[str] | None = "920d7a54afc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column(
            "device_family",
            sa.String(length=32),
            server_default=sa.text("'simulation'"),
            nullable=False,
        ),
    )
    op.create_index("ix_devices_family", "devices", ["device_family"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_devices_family", table_name="devices")
    op.drop_column("devices", "device_family")
    # ### end Alembic commands ###
